pacman::p_load(tidyverse)




dathw <- read_csv("../../htwtd1.csv") |>
  mutate(nlist = str_split(Player, ","),
         lastn = map(nlist, first),
         firstn = map(nlist, last))

datpd <- read_csv("PortalData_New.csv")


university_names <- c("Abilene Christian", "Air Force", "Akron", "Alabama", "Alabama A&M", "Alabama State",
                      "Albany State", "Alcorn State", "App State", "Arizona", "Arizona State", "Arkansas",
                      "Arkansas State", "Arkansas-Pine Bluff", "Army", "Auburn", "Augustana", "Aurora University",
                      "Austin Peay", "Ball State", "Barton C.C.", "Baylor", "Benedict College", "Bethune-Cookman",
                      "Boise State", "Boston College", "Bowie State", "Bowling Green", "Brown", "Bryant", "Bucknell",
                      "Buffalo", "Butler", "Butler C.C.", "BYU", "Cal Poly", "California", "Campbell", "Carroll College",
                      "Carson-Newman College", "Central Arkansas", "Central Connecticut", "Central Michigan",
                      "Central Missouri", "Central Oklahoma", "Central Washington", "Charlotte", "Chattanooga",
                      "Cincinnati", "Clemson", "Coastal Carolina", "Coffeyville C.C.", "Colorado", "Colorado Mesa",
                      "Colorado School Of Mines", "Colorado State", "Columbia", "Concordia University",
                      "Copiah-Lincoln C.C.", "CSU-Pueblo", "Davenport", "Delaware", "Delaware State", "Delta State",
                      "Duke", "Duquesne", "East Carolina", "East Central (OK)", "East Mississippi C.C.",
                      "East Tennessee State", "Eastern Illinois", "Eastern Kentucky", "Eastern Michigan",
                      "Eastern New Mexico", "Eastern Washington", "Edinboro University", "Edward Waters",
                      "El Camino College", "Elon", "Exeter", "Fairmont State", "Ferris State", "Findlay", "Florida",
                      "Florida A&M", "Florida Atlantic", "Florida International", "Florida State", "Fresno State",
                      "Furman", "Garden City C.C.", "Gardner-Webb", "Georgetown", "Georgia", "Georgia Southern",
                      "Georgia State", "Georgia Tech", "Grambling", "Grand Valley State University", "Hampton",
                      "Harvard", "Hawai'i", "Heidelberg", "Highland C.C.", "Hillsdale College", "Holy Cross",
                      "Houston", "Houston Christian", "Howard", "Idaho", "Idaho State", "Illinois", "Illinois State",
                      "Incarnate Word", "Independence C.C.", "Indiana", "Indiana State", "Iowa", "Iowa State",
                      "Iowa Western C.C.", "Itawamba C.C.", "Jackson State", "Jacksonville State", "James Madison",
                      "Johnson C. Smith University", "Kansas", "Kansas State", "Kennesaw State", "Kent State",
                      "Kentucky", "Kilgore J.C.", "Lafayette", "Lake Erie", "Lamar", "Lenoir-Rhyne", "Liberty",
                      "Lindenwood", "Long Beach City College", "Louisiana", "Louisiana Tech", "Louisville", "LSU",
                      "Maine", "Marist", "Marshall", "Maryland", "Massachusetts", "McNeese", "Memphis", "Mercer",
                      "Miami", "Miami (OH)", "Michigan", "Michigan State", "Middle Tennessee", "Minnesota",
                      "Minnesota Duluth", "Mississippi State", "Missouri", "Missouri S&T", "Missouri Southern State",
                      "Missouri State", "Missouri Western State", "Monmouth", "Montana", "Montana State",
                      "Morehead State", "Morgan State", "Murray State", "Navarro College", "Navy", "NC State",
                      "Nebraska", "Nebraska Kearney", "Nevada", "New Mexico", "New Mexico State", "Nicholls",
                      "Norfolk State", "North Alabama", "North Carolina", "North Carolina A&T", "North Carolina Central",
                      "North Dakota", "North Dakota State", "North Texas", "Northern Arizona", "Northern Colorado",
                      "Northern Illinois", "Northern Iowa", "Northern State", "Northwest Missouri St", "Northwestern",
                      "Northwestern State", "Notre Dame", "Notre Dame College", "Ohio", "Ohio State", "Oklahoma",
                      "Oklahoma State", "Old Dominion", "Ole Miss", "Oregon", "Oregon State", "Penn State",
                      "Pennsylvania", "Pikeville", "Pittsburg St", "Pittsburgh", "Portland State", "Prairie View A&M",
                      "Presbyterian", "Purdue", "Rhode Island", "Rice", "Robert Morris", "Rutgers", "Sacramento State",
                      "Sacred Heart", "Saginaw Valley State", "Saint Francis", "Saint Francis (PA)", "Sam Houston",
                      "Samford", "San Diego", "San Diego State", "San José State", "SE Louisiana", "Slippery Rock",
                      "SMU", "South Alabama", "South Carolina", "South Carolina State", "South Dakota",
                      "South Dakota State", "South Florida", "Southeast Missouri State", "Southeast Oklahoma State",
                      "Southern", "Southern Illinois", "Southern Miss", "Southern Utah", "Southwestern College",
                      "Stanford", "Stephen F. Austin", "Stetson", "Stony Brook", "Syracuse", "Tarleton State", "Taylor",
                      "TCU", "Temple", "Tennessee", "Tennessee State", "Tennessee Tech", "Texas", "Texas A&M",
                      "Texas Southern", "Texas State", "Texas Tech", "The Citadel", "Tiffin University", "Toledo",
                      "Towson", "Trinity Valley C.C.", "Troy", "Tulane", "Tulsa", "Tyler J.C.", "UAB", "UAlbany",
                      "UC Davis", "UCF", "UCLA", "UConn", "UL Monroe", "UNLV", "USC", "UT Martin", "Utah", "Utah State",
                      "Utah Tech", "UTEP", "UTSA", "Valdosta State", "Vanderbilt", "Virginia", "Virginia Tech",
                      "Virginia Union", "VMI", "Wagner", "Wake Forest", "Washington", "Washington State", "Wayne State",
                      "Weber State", "West Florida", "West Georgia", "West Virginia", "Western Illinois",
                      "Western Kentucky", "Western Michigan", "William & Mary", "Wisconsin", "Wofford", "Wyoming",
                      "Youngstown State")


lazy_abbreviations <- c("Abilene Christian", "Air Force", "Akron", "Alabama", "Alabama A&M", "Alabama State",
                        "Albany State", "Alcorn State", "App State", "Arizona", "Arizona State", "Arkansas",
                        "Arkansas State", "Arkansas-Pine Bluff", "Army", "Auburn", "Augustana", "Aurora University",
                        "Austin Peay", "Ball State", "Barton C.C.", "Baylor", "Benedict College", "Bethune-Cookman",
                        "Boise State", "Boston College", "Bowie State", "Bowling Green", "Brown", "Bryant", "Bucknell",
                        "Buffalo", "Butler", "Butler C.C.", "BYU", "Cal Poly", "California", "Campbell", "Carroll College",
                        "Carson-Newman College", "Central Arkansas", "Central Connecticut", "Central Michigan",
                        "Central Missouri", "Central Oklahoma", "Central Washington", "Charlotte", "Chattanooga",
                        "Cincinnati", "Clemson", "Coastal Carolina", "Coffeyville C.C.", "Colorado", "Colorado Mesa",
                        "Colorado School Of Mines", "Colorado State", "Columbia", "Concordia University",
                        "Copiah-Lincoln C.C.", "CSU-Pueblo", "Davenport", "Delaware", "Delaware State", "Delta State",
                        "Duke", "Duquesne", "East Carolina", "East Central (OK)", "East Mississippi C.C.",
                        "East Tennessee State", "Eastern Illinois", "Eastern Kentucky", "Eastern Michigan",
                        "Eastern New Mexico", "Eastern Washington", "Edinboro University", "Edward Waters",
                        "El Camino College", "Elon", "Exeter", "Fairmont State", "Ferris State", "Findlay", "Florida",
                        "Florida A&M", "Florida Atlantic", "Florida International", "Florida State", "Fresno State",
                        "Furman", "Garden City C.C.", "Gardner-Webb", "Georgetown", "Georgia", "Georgia Southern",
                        "Georgia State", "Georgia Tech", "Grambling", "Grand Valley State University", "Hampton",
                        "Harvard", "Hawai'i", "Heidelberg", "Highland C.C.", "Hillsdale College", "Holy Cross",
                        "Houston", "Houston Christian", "Howard", "Idaho", "Idaho State", "Illinois", "Illinois State",
                        "Incarnate Word", "Independence C.C.", "Indiana", "Indiana State", "Iowa", "Iowa State",
                        "Iowa Western C.C.", "Itawamba C.C.", "Jackson State", "Jacksonville State", "James Madison",
                        "Johnson C. Smith University", "Kansas", "Kansas State", "Kennesaw State", "Kent State",
                        "Kentucky", "Kilgore J.C.", "Lafayette", "Lake Erie", "Lamar", "Lenoir-Rhyne", "Liberty",
                        "Lindenwood", "Long Beach City College", "Louisiana", "Louisiana Tech", "Louisville", "LSU",
                        "Maine", "Marist", "Marshall", "Maryland", "Massachusetts", "McNeese", "Memphis", "Mercer",
                        "Miami", "Miami (OH)", "Michigan", "Michigan State", "Middle Tennessee", "Minnesota",
                        "Minnesota Duluth", "Mississippi State", "Missouri", "Missouri S&T", "Missouri Southern State",
                        "Missouri State", "Missouri Western State", "Monmouth", "Montana", "Montana State",
                        "Morehead State", "Morgan State", "Murray State", "Navarro College", "Navy", "NC State",
                        "Nebraska", "Nebraska Kearney", "Nevada", "New Mexico", "New Mexico State", "Nicholls",
                        "Norfolk State", "North Alabama", "North Carolina", "North Carolina A&T", "North Carolina Central",
                        "North Dakota", "North Dakota State", "North Texas", "Northern Arizona", "Northern Colorado",
                        "Northern Illinois", "Northern Iowa", "Northern State", "Northwest Missouri St", "Northwestern",
                        "Northwestern State", "Notre Dame", "Notre Dame College", "Ohio", "Ohio State", "Oklahoma",
                        "Oklahoma State", "Old Dominion", "Ole Miss", "Oregon", "Oregon State", "Penn State",
                        "Pennsylvania", "Pikeville", "Pittsburg St", "Pittsburgh", "Portland State", "Prairie View A&M",
                        "Presbyterian", "Purdue", "Rhode Island", "Rice", "Robert Morris", "Rutgers", "Sacramento State",
                        "Sacred Heart", "Saginaw Valley State", "Saint Francis", "Saint Francis (PA)", "Sam Houston",
                        "Samford", "San Diego", "San Diego State", "San José State", "SE Louisiana", "Slippery Rock",
                        "SMU", "South Alabama", "South Carolina", "South Carolina State", "South Dakota",
                        "South Dakota State", "South Florida", "Southeast Missouri State", "Southeast Oklahoma State",
                        "Southern", "Southern Illinois", "Southern Miss", "Southern Utah", "Southwestern College",
                        "Stanford", "Stephen F. Austin", "Stetson", "Stony Brook", "Syracuse", "Tarleton State", "Taylor",
                        "TCU", "Temple", "Tennessee", "Tennessee State", "Tennessee Tech", "Texas", "Texas A&M",
                        "Texas Southern", "Texas State", "Texas Tech", "The Citadel", "Tiffin University", "Toledo",
                        "Towson", "Trinity Valley C.C.", "Troy", "Tulane", "Tulsa", "Tyler J.C.", "UAB", "UAlbany",
                        "UC Davis", "UCF", "UCLA", "UConn", "UL Monroe", "UNLV", "USC", "UT Martin", "Utah", "Utah State",
                        "Utah Tech", "UTEP", "UTSA", "Valdosta State", "Vanderbilt", "Virginia", "Virginia Tech",
                        "Virginia Union", "VMI", "Wagner", "Wake Forest", "Washington", "Washington State", "Wayne State",
                        "Weber State", "West Florida", "West Georgia", "West Virginia", "Western Illinois",
                        "Western Kentucky", "Western Michigan", "William & Mary", "Wisconsin", "Wofford", "Wyoming",
                        "Youngstown State")
acronyms <- c("AFA", "AKR", "ALA", "APP", "ARIZ", "ARK", "ARMY", "ARST", "ASU", "AUB", "BALL", "BAY", "BC", "BGSU",
              "BSU", "BUFF", "BYU", "CAL", "CCU", "CHAR", "CIN", "CLEM", "CMU", "COLO", "CONN", "CSU", "DUKE",
              "ECU", "EMU", "FAU", "FIU", "FLA", "FRES", "FSU", "GASO", "GSU", "GT", "HAW", "HOU", "ILL", "IOWA",
              "ISU", "IU", "JMU", "JSU", "KENN", "KENT", "KSU", "KU", "LIB", "LOU", "LSU", "LT", "MASS", "MD",
              "MEM", "MIA", "MICH", "MINN", "MISS", "MIZZ", "M-OH", "MRSH", "MSST", "MSU", "MTU", "NAVY", "NCST",
              "ND", "NEB", "NEV", "NIU", "NMSU", "NW", "ODU", "OHIO", "OKLA", "OKST", "ORE", "ORST", "OSU", "PITT",
              "PSU", "PUR", "RICE", "RUTG", "SDSU", "SHSU", "SJSU", "SMU", "SOCAR", "STAN", "SYR", "TAM", "TCU",
              "TEM", "TENN", "TEX", "TLSA", "TOL", "TROY", "TTU", "TULN", "TXST", "UAB", "UCF", "UCLA", "UGA",
              "UK", "ULL", "ULM", "UNC", "UNLV", "UNM", "UNT", "USA", "USC", "USF", "USM", "USU", "UTAH", "UTEP",
              "UTSA", "UVA", "VAN", "VT", "WAKE", "WASH", "WIS", "WKU", "WMU", "WSU", "WVU", "WYO")

library(DT)

# Create a data frame with university names, acronyms, and lazy abbreviations
universities <- data.frame(
  University = c("Abilene Christian", "Air Force", "Akron", "Alabama", "Alabama A&M", "Alabama State", "Albany State", "Alcorn State", "App State", "Arizona", "Arizona State", "Arkansas", "Arkansas State", "Arkansas-Pine Bluff", "Army", "Auburn", "Augustana", "Aurora University", "Austin Peay", "Ball State", "Barton C.C.", "Baylor", "Benedict College", "Bethune-Cookman", "Boise State", "Boston College", "Bowie State", "Bowling Green", "Brown", "Bryant", "Bucknell", "Buffalo", "Butler", "Butler C.C.", "BYU", "Cal Poly", "California", "Campbell", "Carroll College", "Carson-Newman College"),
  Acronym = c("AFA", "AKR", "ALA", "APP", "ARIZ", "ARK", "ARMY", "ARST", "ASU", "AUB", "BALL", "BAY", "BC", "BGSU", "BSU", "BUFF", "BYU", "CAL", "CCU", "CHAR", "CIN", "CLEM", "CMU", "COLO", "CONN", "CSU", "DUKE", "ECU", "EMU", "FAU", "FIU", "FLA", "FRES", "FSU", "GASO", "GSU", "GT", "HAW", "HOU", "ILL"),
  LazyAbbreviation = c("Abilene", "Air", "Akron", "Bama", "AAMU", "ASU", "Albany", "Alcorn", "App", "Zona", "ASU", "Ark", "ArSt", "APB", "Army", "Aub", "Aug", "Aurora", "Peay", "Ball", "Barton", "Bay", "Benedict", "BC", "Boise", "BC", "Bowie", "BG", "Brown", "Bryant", "Buck", "Buff", "Butler", "ButlerCC", "BYU", "Poly", "Cal", "Camp", "Carroll", "CNC")
)

# Create the datatable
datatable(universities, options = list(pageLength = 10), rownames = FALSE)

